inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 3.0
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - !ruby/regexp /old_and_unused\.rb$/

Rails/FilePath:
  Exclude:
    - 'lib/tasks/dev.rake'
    - 'spec/rails_helper.rb'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# scopeにおける->表記を許可
Style/Lambda:
  Enabled: false

# private/protect内ではインデントを一つ下げる
Style/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

# テストコードに関してはトータル行数を無視
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'