version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/intelist
      - public-data:/intelist/public
      - tmp-data:/intelist/tmp
      - log-data:/intelist/log
      - ~/.ssh:/root/.ssh
    depends_on:
      - db
  db:
    image: mysql:8.0
    command:
      --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
      dockerfile: Dockerfile.dev
    volumes:
      - public-data:/intelist/public
      - tmp-data:/intelist/tmp
    ports:
      - 80:80
    depends_on:
      - app
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: