FROM ruby:3.0.2

RUN apt-get update -qq && \
    apt-get install -y build-essential \
                       nodejs

RUN apt-get update && apt-get install -y curl apt-transport-https wget && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - 
RUN apt-get autoremove -y nodejs && \
    apt-get install -y -f nodejs


RUN mkdir /intelist
WORKDIR /intelist

ADD Gemfile /intelist/Gemfile
ADD Gemfile.lock /intelist/Gemfile.lock

RUN bundle install

ADD . /intelist

RUN mkdir -p tmp/sockets